name = "zevenstone-contact-api"
main = "src/index.ts"
compatibility_date = "2024-04-30"

[vars]
SANITY_PROJECT_ID = "h79epwt4"
SANITY_DATASET = "production"
SANITY_WRITE_TOKEN = "skFWn2ogh2ytjdOXwi3VegmHKtb5gAz7c7JgUNEQiB74SpSzRy3H83LOudohcxyaXFrckhaxqwrW0R0IqUntuRnGWLnYdp4WF3JHxChCwvCjnxLensWsmPx20GM5sUdhfTqZkzzYKtsiT0qBv4RHcYPKhwrU9AeIBUYGSsFFoBF6WLuVz9jc"
BIGIN_PUBLIC_KEY = "8ce9ae4420af6e6b383435d4f52b629093884f5eeb7c2265346c665ec9c1f57c"
BIGIN_FORM_ID = "d04f04b6a306e599886c66f34da090d2c4ab8389efddf4da2017048958b59c986cd48ef5c5cc554f7160fb3402a6bc62"
